parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     mathsup
    database_user:     root
    database_password: ~

    mailer_transport:  gmail
    mailer_host:       ~
    mailer_user:       kevin.i-class@gmail.com
    mailer_password:   berchiol

    locale:            fr
    secret:            ThisTokenIsNotSoSecretChangeIt

# Pour la pagination
    departement:        10
    qcm:                10
    chapitre:           10
    excerccice_corrige: 10