services:
    msp_user.registration.form.type:
        class: Msp\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: msp_user_registration }
    
    msp_user.profile.form.type:
        class: Msp\UserBundle\Form\Type\ProfileFormType
        arguments: ["@service_container",%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: msp_user_profile }
