<?php

namespace Msp\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QcmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QcmRepository extends EntityRepository
{
    public function getTotal()
    {
        $qb = $this->createQueryBuilder('a')->select('COUNT(a)'); 
        return (int) $qb->getQuery()->getSingleScalarResult();
    } 
    
    public function getByNiveauOrderByDifficulter( $niveau, $limit, $offset = 0 )
    {       
        $qb =   $this->createQueryBuilder('a')                
                ->innerJoin('a.difficulter', 'd')
                ->where('a.niveau = :niveau')
                ->setParameter( 'niveau', $niveau )
                ->orderBy('d.nombreEtoile', 'ASC');
        
        return $qb->getQuery()->setMaxResults($limit)->setFirstResult($offset)->getResult();
    }
}
