<?php

namespace Msp\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserAvailabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHourlyRateRepository extends EntityRepository
{
    public function getAllForUser( $user )
    {
        $qb =   $this->createQueryBuilder('a')
                ->where('a.user = :user')
                ->setParameter('user', $user)
                ->orderBy('a.cours', 'ASC');
        
        return $qb->getQuery()->getResult();
    }
}
