#
# Route de la page d'accueil #
#
msp_frontend_homepage:
    pattern:  /
    defaults: { _controller: MspFrontendBundle:Frontend:index }

msp_conference_connexion:
    pattern:  /conference/connexion/
    defaults: { _controller: MspFrontendBundle:Frontend:connexionConference }

msp_conference_form:
    pattern:  /conference/connexion/form/
    defaults: { _controller: MspFrontendBundle:Frontend:connexionConferenceForm }

msp_conference_avis:
    pattern:  /conference/avis/{slug}/
    defaults: { _controller: MspFrontendBundle:Frontend:conferenceAvis }
#
# Les routes inscription #
#
msp_eleve_inscription:
    pattern:  /inscription/eleve/
    defaults: { _controller: MspUserBundle:Registration:registerEleve }

#msp_professeur_inscription:
#    pattern:  /inscription/professeur/
#    defaults: { _controller: MspUserBundle:Registration:register, role: ROLE_PROFESSEUR }

#
# Les routes des eleves #
#
msp_eleve:
    pattern:  /eleve/profile/{slug}/
    defaults: { _controller: MspFrontendBundle:Frontend:eleve }

msp_eleve_corriges:
    pattern:  /eleve/corriges/{page}/
    defaults: { _controller: MspFrontendBundle:Frontend:eleveCorriges, page: 1 }
    requirements:
        page: \d*

msp_eleve_corriges_show:
    pattern:  /eleve/corriges/show/{id}/
    defaults: { _controller: MspFrontendBundle:Frontend:eleveCorrigesShow }

msp_eleve_qcm:
    pattern:  /eleve/qcm/
    defaults: { _controller: MspFrontendBundle:Frontend:eleveQcm }

msp_eleve_qcm_test:
    pattern:  /eleve/qcm/{qcm_id}/{question_id}/
    defaults: { _controller: MspFrontendBundle:Frontend:eleveQcmTest, question_id: 1 }

msp_eleve_ticket:
    pattern:  /eleve/ticket/
    defaults: { _controller: MspFrontendBundle:Frontend:eleveTicket }

msp_eleve_ticket_ajouter:
    pattern:  /eleve/ticket/ajouter/
    defaults: { _controller: MspFrontendBundle:Frontend:eleveTicketAjouter }

msp_eleve_ticket_show:
    pattern:  /eleve/ticket/show/{id}/
    defaults: { _controller: MspFrontendBundle:Frontend:eleveTicketShow }

#
# Les routes des professeurs #
#
msp_professeur:
    pattern:  /professeur/profile/{slug}/
    defaults: { _controller: MspFrontendBundle:Frontend:professeur }

msp_professeur_conference_create:
    pattern:  /professeur/conference/create/
    defaults: { _controller: MspFrontendBundle:Conference:create}

msp_professeur_conference_new:
    pattern:  /professeur/conference/new/
    defaults: { _controller: MspFrontendBundle:Conference:new}

msp_professeur_conference_show:
    pattern:  /professeur/conference/show/{id}
    defaults: { _controller: MspFrontendBundle:Conference:show}

msp_professeur_conference_edit:
    pattern:  /professeur/conference/edit/{id}
    defaults: { _controller: MspFrontendBundle:Conference:edit}

msp_professeur_conference_update:
    pattern:  /professeur/conference/update/{id}
    defaults: { _controller: MspFrontendBundle:Conference:update}

msp_professeur_conference_delete:
    pattern:  /professeur/conference/delete/{id}
    defaults: { _controller: MspFrontendBundle:Conference:delete }

msp_professeur_conference:
    pattern:  /professeur/conference/{page}/
    defaults: { _controller: MspFrontendBundle:Conference:index, page:1 }
    requirements:
        page: \d*

msp_professeur_planning:
    pattern:  /professeur/planning/{slug}/
    defaults: { _controller: MspFrontendBundle:Frontend:planning }

msp_professeur_planning_edit:
    pattern:  /planning/edit/{user_slug}/{cours_id}/{timetamp}/{disponibilite}/
    defaults: { _controller: MspFrontendBundle:Frontend:planningEdit }

msp_professeur_ticket:
    pattern:  /professeur/ticket/
    defaults: { _controller: MspFrontendBundle:Frontend:professeurTicket }

msp_professeur_bilan_mensuel:
    pattern:  /professeur/bilan-mensuel/
    defaults: { _controller: MspFrontendBundle:Frontend:professeurBilanMensuel }

msp_professeur_fiche_paie:
    pattern:  /professeur/fiche-paie/
    defaults: { _controller: MspFrontendBundle:Frontend:professeurFichePaie }

#
# Les routes des administrateurs #
#
msp_admin:
    pattern:  /admin/profile/{slug}/
    defaults: { _controller: MspFrontendBundle:Frontend:admin }

#
# Les routes des pages statiques #
#
msp_qui_sommes_nous:
    pattern:  /qui-sommes-nous/
    defaults: { _controller: MspFrontendBundle:Frontend:quiSommesNous }

msp_contact:
    pattern:  /contact/
    defaults: { _controller: MspFrontendBundle:Frontend:contact }

msp_math_plus:
    pattern:  /math-plus/
    defaults: { _controller: MspFrontendBundle:Frontend:mathPlus }

msp_faq:
    pattern:  /FAQ/
    defaults: { _controller: MspFrontendBundle:Frontend:faq }

msp_primaire:
    pattern:  /primaire/
    defaults: { _controller: MspFrontendBundle:Frontend:primaire }

msp_college:
    pattern:  /college/
    defaults: { _controller: MspFrontendBundle:Frontend:college }

msp_lycee:
    pattern:  /lycee/
    defaults: { _controller: MspFrontendBundle:Frontend:lycee }    

msp_universite:
    pattern:  /universite/
    defaults: { _controller: MspFrontendBundle:Frontend:universite }

msp_universite_section:
    pattern:  /universite/{page}/
    defaults: { _controller: MspFrontendBundle:Frontend:universite }

msp_institution:
    pattern:  /institution/
    defaults: { _controller: MspFrontendBundle:Frontend:institution }

msp_tarifs:
    pattern:  /tarifs/
    defaults: { _controller: MspFrontendBundle:Frontend:tarifs }

msp_partenariats:
    pattern:  /partenariats/
    defaults: { _controller: MspFrontendBundle:Frontend:partenariats }

msp_nos_engagements:
    pattern:  /nos-engagements/
    defaults: { _controller: MspFrontendBundle:Frontend:nosEngagements }

msp_cgs:
    pattern:  /CGS/
    defaults: { _controller: MspFrontendBundle:Frontend:cgs }

msp_plan_du_site:
    pattern:  /plan_du_site/
    defaults: { _controller: MspFrontendBundle:Frontend:planDuSite }

msp_liens:
    pattern:  /liens/
    defaults: { _controller: MspFrontendBundle:Frontend:liens }

msp_newsletter:
    pattern:  /newsletter/
    defaults: { _controller: MspFrontendBundle:Frontend:newsletter }

#
# Les routes pour niveau #
#
niveau:
    pattern:  /niveau/
    defaults: { _controller: MspFrontendBundle:Niveau:index }

niveau_create:
    pattern:  /niveau/create/
    defaults: { _controller: MspFrontendBundle:Niveau:create }

niveau_new:
    pattern:  /niveau/new/
    defaults: { _controller: MspFrontendBundle:Niveau:new}

niveau_show:
    pattern:  /niveau/show/{id}
    defaults: { _controller: MspFrontendBundle:Niveau:show}

niveau_edit:
    pattern:  /niveau/edit/{id}
    defaults: { _controller: MspFrontendBundle:Niveau:edit}

niveau_update:
    pattern:  /niveau/update/{id}
    defaults: { _controller: MspFrontendBundle:Niveau:update}

niveau_delete:
    pattern:  /niveau/delete/{id}
    defaults: { _controller: MspFrontendBundle:Niveau:delete}

#
# Les routes pour Departement #
#
departement:
    pattern:  /departement/{page}/
    defaults: { _controller: MspFrontendBundle:Departement:index, page: 1 }
    requirements:
        page: \d*

departement_create:
    pattern:  /departement/create/
    defaults: { _controller: MspFrontendBundle:Departement:create}

departement_new:
    pattern:  /departement/new/
    defaults: { _controller: MspFrontendBundle:Departement:new}

departement_show:
    pattern:  /departement/show/{id}
    defaults: { _controller: MspFrontendBundle:Departement:show}

departement_edit:
    pattern:  /departement/edit/{id}
    defaults: { _controller: MspFrontendBundle:Departement:edit}

departement_update:
    pattern:  /departement/update/{id}
    defaults: { _controller: MspFrontendBundle:Departement:update}

departement_delete:
    pattern:  /departement/delete/{id}
    defaults: { _controller: MspFrontendBundle:Departement:delete}

#
# Les routes pour COURS #
#
cours:
    pattern:  /cours/
    defaults: { _controller: MspFrontendBundle:Cours:index }

cours_create:
    pattern:  /cours/create/
    defaults: { _controller: MspFrontendBundle:Cours:create}

cours_new:
    pattern:  /cours/new/
    defaults: { _controller: MspFrontendBundle:Cours:new}

cours_show:
    pattern:  /cours/show/{id}
    defaults: { _controller: MspFrontendBundle:Cours:show}

cours_edit:
    pattern:  /cours/edit/{id}
    defaults: { _controller: MspFrontendBundle:Cours:edit}

cours_update:
    pattern:  /cours/update/{id}
    defaults: { _controller: MspFrontendBundle:Cours:update}

cours_delete:
    pattern:  /cours/delete/{id}
    defaults: { _controller: MspFrontendBundle:Cours:delete }

#
# Les routes pour Classe #
#
classe:
    pattern:  /classe/
    defaults: { _controller: MspFrontendBundle:Classe:index }

classe_create:
    pattern:  /classe/create/
    defaults: { _controller: MspFrontendBundle:Classe:create}

classe_new:
    pattern:  /classe/new/
    defaults: { _controller: MspFrontendBundle:Classe:new}

classe_show:
    pattern:  /classe/show/{id}
    defaults: { _controller: MspFrontendBundle:Classe:show}

classe_edit:
    pattern:  /classe/edit/{id}
    defaults: { _controller: MspFrontendBundle:Classe:edit}

classe_update:
    pattern:  /classe/update/{id}
    defaults: { _controller: MspFrontendBundle:Classe:update}

classe_delete:
    pattern:  /classe/delete/{id}
    defaults: { _controller: MspFrontendBundle:Classe:delete}

#
# Les routes pour chapitre #
#
chapitre:
    pattern:  /chapitre/{page}/
    defaults: { _controller: MspFrontendBundle:Chapitre:index, page:1 }
    requirements:
        page: \d*

chapitre_create:
    pattern:  /chapitre/create/
    defaults: { _controller: MspFrontendBundle:Chapitre:create}

chapitre_new:
    pattern:  /chapitre/new/
    defaults: { _controller: MspFrontendBundle:Chapitre:new}

chapitre_show:
    pattern:  /chapitre/show/{id}
    defaults: { _controller: MspFrontendBundle:Chapitre:show}

chapitre_edit:
    pattern:  /chapitre/edit/{id}
    defaults: { _controller: MspFrontendBundle:Chapitre:edit}

chapitre_update:
    pattern:  /chapitre/update/{id}
    defaults: { _controller: MspFrontendBundle:Chapitre:update}

chapitre_delete:
    pattern:  /chapitre/delete/{id}
    defaults: { _controller: MspFrontendBundle:Chapitre:delete}

#
# Les routes pour ExerciceCorrige #
#
exercicecorrige:
    pattern:  /exercicecorrige/{page}/
    defaults: { _controller: MspFrontendBundle:ExerciceCorrige:index, page: 1 }
    requirements:
        page: \d*

exercicecorrige_create:
    pattern:  /exercicecorrige/create/
    defaults: { _controller: MspFrontendBundle:ExerciceCorrige:create}

exercicecorrige_new:
    pattern:  /exercicecorrige/new/
    defaults: { _controller: MspFrontendBundle:ExerciceCorrige:new}

exercicecorrige_show:
    pattern:  /exercicecorrige/show/{id}
    defaults: { _controller: MspFrontendBundle:ExerciceCorrige:show}

exercicecorrige_edit:
    pattern:  /exercicecorrige/edit/{id}
    defaults: { _controller: MspFrontendBundle:ExerciceCorrige:edit}

exercicecorrige_update:
    pattern:  /exercicecorrige/update/{id}
    defaults: { _controller: MspFrontendBundle:ExerciceCorrige:update}

exercicecorrige_delete:
    pattern:  /exercicecorrige/delete/{id}
    defaults: { _controller: MspFrontendBundle:ExerciceCorrige:delete}

#
# Les routes pour DIFFICULTER #
#
difficulter:
    pattern:  /difficulter/
    defaults: { _controller: MspFrontendBundle:Difficulter:index }

difficulter_create:
    pattern:  /difficulter/create/
    defaults: { _controller: MspFrontendBundle:Difficulter:create}

difficulter_new:
    pattern:  /difficulter/new/
    defaults: { _controller: MspFrontendBundle:Difficulter:new}

difficulter_show:
    pattern:  /difficulter/show/{id}
    defaults: { _controller: MspFrontendBundle:Difficulter:show}

difficulter_edit:
    pattern:  /difficulter/edit/{id}
    defaults: { _controller: MspFrontendBundle:Difficulter:edit}

difficulter_update:
    pattern:  /difficulter/update/{id}
    defaults: { _controller: MspFrontendBundle:Difficulter:update}

difficulter_delete:
    pattern:  /difficulter/delete/{id}
    defaults: { _controller: MspFrontendBundle:Difficulter:delete}

#
# Les routes pour QCM #
#
qcm:
    pattern:  /qcm/{page}/
    defaults: { _controller: MspFrontendBundle:Qcm:index, page:1 }
    requirements:
        page: \d*

qcm_create:
    pattern:  /qcm/create/
    defaults: { _controller: MspFrontendBundle:Qcm:create}

qcm_new:
    pattern:  /qcm/new/
    defaults: { _controller: MspFrontendBundle:Qcm:new}

qcm_show:
    pattern:  /qcm/show/{id}
    defaults: { _controller: MspFrontendBundle:Qcm:show}

qcm_edit:
    pattern:  /qcm/edit/{id}
    defaults: { _controller: MspFrontendBundle:Qcm:edit}

qcm_update:
    pattern:  /qcm/update/{id}
    defaults: { _controller: MspFrontendBundle:Qcm:update}

qcm_delete:
    pattern:  /qcm/delete/{id}
    defaults: { _controller: MspFrontendBundle:Qcm:delete }

#
# Les routes pour REPONSE #
#
question:
    pattern:  /question/
    defaults: { _controller: MspFrontendBundle:Question:index }

question_create:
    pattern:  /question/create/
    defaults: { _controller: MspFrontendBundle:Question:create}

question_new:
    pattern:  /question/new/
    defaults: { _controller: MspFrontendBundle:Question:new}

question_show:
    pattern:  /question/show/{id}
    defaults: { _controller: MspFrontendBundle:Question:show}

question_edit:
    pattern:  /question/edit/{id}
    defaults: { _controller: MspFrontendBundle:Question:edit}

question_update:
    pattern:  /question/update/{id}
    defaults: { _controller: MspFrontendBundle:Question:update}

question_delete:
    pattern:  /question/delete/{id}
    defaults: { _controller: MspFrontendBundle:Question:delete }

#
# Les routes pour REPONSE #
#
reponse:
    pattern:  /reponse/
    defaults: { _controller: MspFrontendBundle:Reponse:index }

reponse_create:
    pattern:  /reponse/create/
    defaults: { _controller: MspFrontendBundle:Reponse:create}

reponse_new:
    pattern:  /reponse/new/
    defaults: { _controller: MspFrontendBundle:Reponse:new}

reponse_show:
    pattern:  /reponse/show/{id}
    defaults: { _controller: MspFrontendBundle:Reponse:show}

reponse_edit:
    pattern:  /reponse/edit/{id}
    defaults: { _controller: MspFrontendBundle:Reponse:edit}

reponse_update:
    pattern:  /reponse/update/{id}
    defaults: { _controller: MspFrontendBundle:Reponse:update}

reponse_delete:
    pattern:  /reponse/delete/{id}
    defaults: { _controller: MspFrontendBundle:Reponse:delete }

#
# Les routes pour LA GESTION DES ELEVES #
#
eleve:
    pattern:  /eleve/departement/{departement}/classe/{classe}/
    defaults: { _controller: MspFrontendBundle:Eleve:index, departement: 0, classe: 0 }
    requirements:
        departement: \d*
        classe:      \d*

eleve_show:
    pattern:  /eleve/show/{id}
    defaults: { _controller: MspFrontendBundle:Eleve:show}

eleve_edit:
    pattern:  /eleve/edit/{id}
    defaults: { _controller: MspFrontendBundle:Eleve:edit}

eleve_update:
    pattern:  /eleve/update/{id}
    defaults: { _controller: MspFrontendBundle:Eleve:update}

eleve_delete:
    pattern:  /eleve/delete/{id}
    defaults: { _controller: MspFrontendBundle:Eleve:delete }

eleve_ticket:
    pattern:  /admin/eleve/ticket/{id}/
    defaults: { _controller: MspFrontendBundle:Eleve:eleveTicket }
    requirements:
        id: \d+

eleve_ticket_ajouter:
    pattern:  /admin/eleve/ticket/ajouter/{id}/
    defaults: { _controller: MspFrontendBundle:Eleve:eleveTicketAjouter }

eleve_ticket_show:
    pattern:  /admin/eleve/ticket/show/{id}/{user_id}/
    defaults: { _controller: MspFrontendBundle:Eleve:eleveTicketShow }


#
# Les routes pour LA GESTION DES Professeurs #
#
professeur:
    pattern:  /professeur/departement/{departement}/
    defaults: { _controller: MspFrontendBundle:Professeur:index, departement: 0 }
    requirements:
        departement: \d*

professeur_show:
    pattern:  /professeur/show/{id}
    defaults: { _controller: MspFrontendBundle:Professeur:show}

professeur_edit:
    pattern:  /professeur/edit/{id}
    defaults: { _controller: MspFrontendBundle:Professeur:edit}

professeur_update:
    pattern:  /professeur/update/{id}
    defaults: { _controller: MspFrontendBundle:Professeur:update}

professeur_delete:
    pattern:  /professeur/delete/{id}
    defaults: { _controller: MspFrontendBundle:Professeur:delete }

professeur_taux_edit:
    pattern:  /professeur/taux/edit/{user_id}/{cours_id}/{niveau_id}/
    defaults: { _controller: MspFrontendBundle:Professeur:tauxEdit }

professeur_taux:
    pattern:  /professeur/taux/{id}/
    defaults: { _controller: MspFrontendBundle:Professeur:taux }

professeur_bilan_mensuel:
    pattern:  /admin/professeur/bilan-mensuel/{id}/
    defaults: { _controller: MspFrontendBundle:Professeur:professeurBilanMensuel }

professeur_fiche_paie:
    pattern:  /admin/professeur/fiche-paie/{id}/{type}/
    defaults: { _controller: MspFrontendBundle:Professeur:professeurFichePaie, type: html }
#
# Les routes pour les pdf
#
ms_pdf_fiche_paie:
    pattern:  /pdf-fiche-paie/{id}/{action}/
    defaults: { _controller: MspFrontendBundle:Professeur:pdfFichePaie, action: print }

#
# Les routes pour les barcodes
#
ms_barcode:
    pattern:  /barcode/{code}/
    defaults: { _controller: MspFrontendBundle:Frontend:barcode }
